name: MLOps Predictive Maintenance Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Data Preprocessing
        run: python src/preprocessing.py
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}

      - name: Train and Register Model
        run: python src/model_training.py
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}

      - name: Push to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://sriranjan-u:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/Sriranjan/Predictive_Maintenance_App
          git push --force hf main
